/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lola
 */
public class AddWordsList {
    
    
    public void addWords(ListWords listWords){
        Words words = new Words("SER O ESTAR","BE","WAS OR WERE");
        listWords.insertWords(words);
        words = new Words("LATIR","BEAT","BEAT");
        listWords.insertWords(words);
        words = new Words("LLEGAR A SER","BECOME","BECAME");
        listWords.insertWords(words);
        words = new Words("EMPEZAR","BEGIN","BEGAN");
        listWords.insertWords(words);
        words = new Words("MODER","BITE","BIT");
        listWords.insertWords(words);
        words = new Words("SOPLAR","BLOW","BLEW");
        listWords.insertWords(words);
        words = new Words("ROMPER","BREAK","BROKE");
        listWords.insertWords(words);
        words = new Words("TRAER","BRING","BROUGHT");
        listWords.insertWords(words);
        words = new Words("CONSTRUIR","BUILD","BUILT");
        listWords.insertWords(words);
        words = new Words("COMPRAR","BUY","BOUGHT");
        listWords.insertWords(words);
        words = new Words("ATRAPAR","CATCH","CAUGHT");
        listWords.insertWords(words);
        words = new Words("ELEGIR","CHOOSE","CHOSE");
        listWords.insertWords(words);
        words = new Words("VENIR","COME","CAME");
        listWords.insertWords(words);
        words = new Words("COSTAR","COST","COST");
        listWords.insertWords(words);
        words = new Words("CORTAR","CUT","CUT");
        listWords.insertWords(words);
        words = new Words("HACER","DO","DID");
        listWords.insertWords(words);
        words = new Words("DIBUJAR","DRAW","DREW");
        listWords.insertWords(words);
        words = new Words("BEBER","DRINK","DRANK");
        listWords.insertWords(words);
        words = new Words("MANEJAR","DRIVE","DROVE");
        listWords.insertWords(words);
        words = new Words("COMER","EAT","ATE");
        listWords.insertWords(words);
        words = new Words("CAER","FALL","FELL");
        listWords.insertWords(words);
        words = new Words("SENTIR","FEEL","FELT");
        listWords.insertWords(words);
        words = new Words("PELEAR","FIGHT","FOUGHT");
        listWords.insertWords(words);
        words = new Words("ENCONTRAR","FIND","FOUND");
        listWords.insertWords(words);
        words = new Words("VOLAR","FLY","FLEW");
        listWords.insertWords(words);
        words = new Words("OLVIDAR","FORGET","FORGOT");
        listWords.insertWords(words);
        words = new Words("OBTENER","GET","GOT");
        listWords.insertWords(words);
        words = new Words("DAR","GIVE","GAVE");
        listWords.insertWords(words);
        words = new Words("IR","GO","WENT");
        listWords.insertWords(words);
        words = new Words("CRECER","GROW","GREW");
        listWords.insertWords(words);
        words = new Words("COLGAR","HAND","HUNG");
        listWords.insertWords(words);
        words = new Words("TENER","HAVE","HAD");
        listWords.insertWords(words);
        words = new Words("OIR","HEAR","HEARD");
        listWords.insertWords(words);
        words = new Words("ESCONDER","HIDE","HID");
        listWords.insertWords(words);
        words = new Words("GOLPEAR","HIT","HIT");
        listWords.insertWords(words);
        words = new Words("SOSTENER","HOLD","HELD");
        listWords.insertWords(words);
        words = new Words("HERIR","HURT","HURT");
        listWords.insertWords(words);
        words = new Words("MANETENER","KEEP","KEPT");
        listWords.insertWords(words);
        words = new Words("SABER CONOCER","KNOW","KNEW");
        listWords.insertWords(words);
        words = new Words("DEJAR","LEAVE","LEFT");
        listWords.insertWords(words);
        words = new Words("PRESTAR","LEND","LENT");
        listWords.insertWords(words);
        
        words = new Words("PERMITIR","LET","LET");
        listWords.insertWords(words);
        words = new Words("ECHARSE","LIE","LAY");
        listWords.insertWords(words);
        words = new Words("ILUMINAR","LIGHT","LIT");
        listWords.insertWords(words);
        words = new Words("PERDER","LOSE","LOST");
        listWords.insertWords(words);
        words = new Words("HACER","MAKE","MADE");
        listWords.insertWords(words);
        words = new Words("SIGNIFICAR","MEAN","MEANT");
        listWords.insertWords(words);
        words = new Words("CONOCER","MEET","MET");
        listWords.insertWords(words);
        words = new Words("PAGAR","PAY","PAID");
        listWords.insertWords(words);
        words = new Words("PONER","PUT","PUT");
        listWords.insertWords(words);
        words = new Words("LEER","READ","READ");
        listWords.insertWords(words);
        words = new Words("MONTAR","RIDE","RODE");
        listWords.insertWords(words);
        words = new Words("SONAR","RING","RANG");
        listWords.insertWords(words);
        words = new Words("ELEVAR","RISE","ROSE");
        listWords.insertWords(words);
        words = new Words("CORRER","RUN","RAN");
        listWords.insertWords(words);
        words = new Words("DECIR","SAY","SAID");
        listWords.insertWords(words);
        words = new Words("VER","SEE","SAW");
        listWords.insertWords(words);
        words = new Words("VENDER","SELL","SOLD");
        listWords.insertWords(words);
        words = new Words("ENVIAR","SEND","SENT");
        listWords.insertWords(words);
        words = new Words("BRILLAR","SHINE","SHONE");
        listWords.insertWords(words);
        words = new Words("DISPARAR","SHOOT","SHOT");
        listWords.insertWords(words);
        words = new Words("MOSTRAR","SHOW","SHOWED");
        listWords.insertWords(words);
        words = new Words("CERRAR","SHUT","SHUT");
        listWords.insertWords(words);
        words = new Words("CANTAR","SING","SANG");
        listWords.insertWords(words);
        words = new Words("SENTARSE","SIT","SAT");
        listWords.insertWords(words);
        words = new Words("DORMIR","SLEEP","SLEPT");
        listWords.insertWords(words);
        words = new Words("HABLAR","SPEAK","SPOKE");
        listWords.insertWords(words);
        words = new Words("GASTAR","SPEND","SPENT");
        listWords.insertWords(words);
        words = new Words("LEVANTARSE","STAND","STOOD");
        listWords.insertWords(words);
        words = new Words("ROBAR","STEAL","STOLE");
        listWords.insertWords(words);
        words = new Words("NADAR","SWIM","SWAM");
        listWords.insertWords(words);
        words = new Words("TOMAR","TAKE","TOOK");
        listWords.insertWords(words);
        words = new Words("ENSEÑAR","TEACH","TAUGHT");
        listWords.insertWords(words);
        words = new Words("RASGAR","TEAR","TORE");
        listWords.insertWords(words);
        words = new Words("CONTAR ALGO","TELL","TOLD");
        listWords.insertWords(words);
        words = new Words("PENSAR","THINK","THOUGHT");
        listWords.insertWords(words);
        words = new Words("LANZAR","THROW","THREW");
        listWords.insertWords(words);
        words = new Words("ENTENDER","UNDERSTAND","UNDERSTOOD");
        listWords.insertWords(words);
        words = new Words("LEVANTARSE","WAKE","WOKEN");
        listWords.insertWords(words);
        words = new Words("VESTIRSE","WEAR","WORE");
        listWords.insertWords(words);
        words = new Words("GANAR","WIN","WON");
        listWords.insertWords(words);
        words = new Words("WRITE","WRITE","WROTE");
        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
//        words = new Words("","","");
//        listWords.insertWords(words);
        
    }
    
}


/*
    words = new Words("","","");
    listWords.insertWords(words);
    words = new Words("","","");
    listWords.insertWords(words);
    words = new Words("","","");
    listWords.insertWords(words);
    words = new Words("","","");
    listWords.insertWords(words);
*/